// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MenulogWebsiteSpecFlowTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RestaurantsCountWithExamples")]
    [NUnit.Framework.CategoryAttribute("RestaurantsCountWithExamples")]
    public partial class RestaurantsCountWithExamplesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RestaurantsCountWithExamples.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "RestaurantsCountWithExamples", "\tIn order to avoid silly mistakes\r\n\tAs a user\r\n\tI want to be told the count of Re" +
                    "staurants in Searched suburb", ProgrammingLanguage.CSharp, new string[] {
                        "RestaurantsCountWithExamples"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Restaurants Count using Examples")]
        [NUnit.Framework.CategoryAttribute("RestaurantsCountWithExamples")]
        [NUnit.Framework.TestCaseAttribute("Westmead", null)]
        [NUnit.Framework.TestCaseAttribute("Harris Park", null)]
        [NUnit.Framework.TestCaseAttribute("Parramatta", null)]
        [NUnit.Framework.TestCaseAttribute("Ajana", null)]
        [NUnit.Framework.TestCaseAttribute("Albany", null)]
        [NUnit.Framework.TestCaseAttribute("Aldersyde", null)]
        [NUnit.Framework.TestCaseAttribute("Alexander Heights", null)]
        public virtual void RestaurantsCountUsingExamples(string suburb, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RestaurantsCountWithExamples"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Restaurants Count using Examples", @__tags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am at the Menulog Home Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And(string.Format("I enter the suburb as {0}", suburb), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then("the restaurant count should be displayed for the searched suburb on the SERP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
